project/project/accounts/urls.py
from django.conf.urls import url

from . import views

project/project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^quiz/', include('quiz.urls')),
]

project/quiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'quiz'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote')
]

project/project/accounts/models.py
from django.db import models

# Create your models here.

project/quiz/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def get_selected_choice_for_user(self, user_id):
        return self.choice_set.filter(voted_users__pk=user_id).first()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    voted_users = models.ManyToManyField(User)

    def __str__(self):
        return self.choice_text

project/project/accounts/views.py
from django.shortcuts import render

# Create your views here.

project/quiz/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice


@login_required()
def index(request):
    only_not_voted = request.GET.get('only_not_voted')
    only_voted = request.GET.get('only_voted')
    offset = int(request.GET.get('offset', 0))
    limit = int(request.GET.get('limit', 10))
    not_voted_questions = None
    voted_questions = None
    now = timezone.now()

    if not only_not_voted:
        voted_questions = Question.objects.filter(
            pub_date__lte=now,
            choice__voted_users__pk=request.user.pk).order_by('-pub_date')[offset:offset+limit]
    if not only_voted:
        not_voted_questions = Question.objects.filter(pub_date__lte=now).exclude(
            choice__voted_users__pk=request.user.pk).order_by('-pub_date')[offset:offset+limit]

    context = {
        'not_voted_questions': not_voted_questions,
        'voted_questions': voted_questions,
        'only_not_voted': only_not_voted,
        'only_voted': only_voted,
        'offset': offset,
        'limit': limit
    }
    return render(request, 'quiz/index.html', context)


@login_required()
def detail(request, question_id):
    question = get_object_or_404(Question, pub_date__lte=timezone.now(), pk=question_id)
    selected_choice = question.get_selected_choice_for_user(request.user.pk)
    if selected_choice:
        return render(request, 'quiz/results.html', {'question': question,
                                                     'selected_choice_pk': selected_choice.pk})
    return render(request, 'quiz/detail.html', {'question': question})


@login_required()
def results(request, question_id):
    question = get_object_or_404(Question, pub_date__lte=timezone.now(), pk=question_id)
    context = {'question': question}
    selected_choice = question.get_selected_choice_for_user(request.user.pk)
    if selected_choice:
        context.update({'selected_choice_pk': selected_choice.pk})
    return render(request, 'quiz/results.html', context)


@login_required()
def vote(request, question_id):
    question = get_object_or_404(Question, pub_date__lte=timezone.now(), pk=question_id)
    if question.get_selected_choice_for_user(request.user.pk):
        return render(request, 'quiz/detail.html', {
            'question': question,
            'error_message': 'You can not vote twice'
        })
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice_id'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'quiz/detail.html', {
            'question': question,
            'error_message': 'You did not choose anything'
        })
    else:
        selected_choice.votes += 1
        selected_choice.voted_users.add(request.user)
        selected_choice.save()
        return HttpResponseRedirect(reverse('quiz:results', args=(question.id,)))


# not in use
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'quiz/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


# not in use
class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'quiz/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


# not in use
class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'quiz/results.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

project/quiz/templates/quiz/detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'quiz:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice_id" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

{% endblock %}

project/quiz/templates/quiz/index.html
{% extends "base.html" %}

{% block content %}

{% if not only_voted %}

<h1><a href={% url 'quiz:index' %}?only_not_voted=1>Not voted question list</h1>

    {% if not_voted_questions %}
        <ul>
        {% for question in not_voted_questions %}
            <li><a href={% url 'quiz:detail' question.id %}>{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <a>No not voted questions are available</a>
    {% endif %}
{% endif %}

{% if not only_not_voted %}

<h1><a href={% url 'quiz:index' %}?only_voted=1>Voted question list</h1>

    {% if voted_questions %}
    <ul>
        {% for question in voted_questions %}
        <li><a href={% url 'quiz:detail' question.id %}>{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <a>No voted questions are available</a>
    {% endif %}
{% endif %}

{% if only_not_voted or only_voted%}

<h3><a href={% url 'quiz:index' %}>Back to all question list</h3>

{% endif %}

{% endblock %}

project/quiz/templates/quiz/results.html
{% extends "base.html" %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        {% if selected_choice_pk == choice.pk %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} << Your vote</li>
        {% else %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock %}

project/templates/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />

{% if user.is_authenticated %}
<form method="post" action="{% url 'logout' %}" id="logout_form">
    {% csrf_token %}
    <div>
        <input type="submit" value="Logout" />
        <input type="hidden" name="next" value="/accounts/login/" />
    </div>
</form>
{% endif %}
{% block content %}{% endblock content %}